### PR TITLE
V 0.0.2

### PR DESCRIPTION
**Pull request by Anish-Shobith**
- [x] Cleaner Code
- [ ] Commands
      - [ ] Admin
      - [ ] Canvas
      - [ ] Configuration
      - [ ] Developer
      - [ ] Economy
      - [ ] Fun
      - [ ] Games
      - [ ] Leveling
      - [ ] Moderation
      - [ ] Music [ Not sure yet ]
- [x] Breaking Change
- [x] Invite Filter

This is decided features are may or may not change!!

### CODE REVIEW

**Comment by officialpiyush** [comment]
uwu

**Comment by piyushc0** [comment]
will see today

**Comment by Anish-Shobith** [comment]
Its still under development when its done i will let u know

**Comment by officialpiyush** [comment]
Lulz

**Comment by officialpiyush** [comment]
Following commit 13dd6fc , u can just pass constants to this.constants.
Like ```js
this.constants = Constants
```

<img align="center" src="https://images.ionadev.ml/i/JBnbEh.jpg" alt="something" />

**Comment by officialpiyush** [comment]
Ay 7db81b0 , broken things, where is language file

**Comment by Anish-Shobith** [comment]
Gonna push tonight, now outside and i am aware of it

**Comment by officialpiyush** [comment]
Cool

**Comment by Anish-Shobith** [comment]
Gonna merge this for now

**Comment by officialpiyush** [comment]
uwu

**Pull request merged**
